import os
import sys

TEMPLATE = """import marimo

__generated_with = "0.1.0"
app = marimo.App()

@app.cell
def __():
    import marimo as mo
    return mo,

@app.cell
def __(mo):
    mo.md(
        \"\"\"
        # New Marimo Notebook

        This notebook was generated by Claude.
        \"\"\"
    )
    return
"""


def scaffold(filename):
    """
    Creates a new valid marimo notebook file.
    """
    if os.path.exists(filename):
        print(f"Error: File '{filename}' already exists.")
        sys.exit(1)

    if not filename.endswith(".py"):
        print("Warning: Marimo files typically end in .py")

    try:
        with open(filename, "w") as f:
            f.write(TEMPLATE)
        print(f"Successfully created marimo notebook: {filename}")
        print("Run 'marimo edit {filename}' to open the editor.")
    except Exception as e:
        print(f"Error creating file: {e}")
        sys.exit(1)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python scaffold_marimo.py <filename.py>")
        sys.exit(1)

    scaffold(sys.argv[1])
